// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift

import Foundation
import Rswift
import UIKit

/// This `R` struct is code generateted, and contains references to static resources.
struct R: Rswift.Validatable {
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 color palettes.
  struct color {
    private init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 3 files.
  struct file {
    /// Resource file `FontAwesome.otf`.
    static let fontAwesomeOtf = FileResource(bundle: _R.hostingBundle, name: "FontAwesome", pathExtension: "otf")
    /// Resource file `GoogleService-Info.plist`.
    static let googleServiceInfoPlist = FileResource(bundle: _R.hostingBundle, name: "GoogleService-Info", pathExtension: "plist")
    /// Resource file `TSMessagesDefaultDesign.json`.
    static let tSMessagesDefaultDesignJson = FileResource(bundle: _R.hostingBundle, name: "TSMessagesDefaultDesign", pathExtension: "json")
    
    /// `bundle.URLForResource("FontAwesome", withExtension: "otf")`
    static func fontAwesomeOtf(_: Void) -> NSURL? {
      let fileResource = R.file.fontAwesomeOtf
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    /// `bundle.URLForResource("GoogleService-Info", withExtension: "plist")`
    static func googleServiceInfoPlist(_: Void) -> NSURL? {
      let fileResource = R.file.googleServiceInfoPlist
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    /// `bundle.URLForResource("TSMessagesDefaultDesign", withExtension: "json")`
    static func tSMessagesDefaultDesignJson(_: Void) -> NSURL? {
      let fileResource = R.file.tSMessagesDefaultDesignJson
      return fileResource.bundle.URLForResource(fileResource)
    }
    
    private init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 1 fonts.
  struct font {
    /// Font `FontAwesome`.
    static let fontAwesome = FontResource(fontName: "FontAwesome")
    
    /// `UIFont(name: "FontAwesome", size: ...)`
    static func fontAwesome(size size: CGFloat) -> UIFont? {
      return UIFont(resource: fontAwesome, size: size)
    }
    
    private init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 6 images.
  struct image {
    /// Image `Baby Pic`.
    static let babyPic = ImageResource(bundle: _R.hostingBundle, name: "Baby Pic")
    /// Image `calendar`.
    static let calendar = ImageResource(bundle: _R.hostingBundle, name: "calendar")
    /// Image `home`.
    static let home = ImageResource(bundle: _R.hostingBundle, name: "home")
    /// Image `interface`.
    static let interface = ImageResource(bundle: _R.hostingBundle, name: "interface")
    /// Image `Line`.
    static let line = ImageResource(bundle: _R.hostingBundle, name: "Line")
    /// Image `people-shout`.
    static let peopleShout = ImageResource(bundle: _R.hostingBundle, name: "people-shout")
    
    /// `UIImage(named: "Baby Pic", bundle: ..., traitCollection: ...)`
    static func babyPic(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.babyPic, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "calendar", bundle: ..., traitCollection: ...)`
    static func calendar(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.calendar, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "home", bundle: ..., traitCollection: ...)`
    static func home(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.home, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "interface", bundle: ..., traitCollection: ...)`
    static func interface(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.interface, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "Line", bundle: ..., traitCollection: ...)`
    static func line(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.line, compatibleWithTraitCollection: traitCollection)
    }
    
    /// `UIImage(named: "people-shout", bundle: ..., traitCollection: ...)`
    static func peopleShout(compatibleWithTraitCollection traitCollection: UITraitCollection? = nil) -> UIImage? {
      return UIImage(resource: R.image.peopleShout, compatibleWithTraitCollection: traitCollection)
    }
    
    private init() {}
  }
  
  private struct intern: Rswift.Validatable {
    static func validate() throws {
      try _R.validate()
    }
    
    private init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 0 nibs.
  struct nib {
    private init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 0 reuse identifiers.
  struct reuseIdentifier {
    private init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    private init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    /// Storyboard `App`.
    static let app = _R.storyboard.app()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `Onboard`.
    static let onboard = _R.storyboard.onboard()
    
    /// `UIStoryboard(name: "App", bundle: ...)`
    static func app(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.app)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "Onboard", bundle: ...)`
    static func onboard(_: Void) -> UIStoryboard {
      return UIStoryboard(resource: R.storyboard.onboard)
    }
    
    private init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    private init() {}
  }
  
  private init() {}
}

struct _R: Rswift.Validatable {
  static let hostingBundle = NSBundle(identifier: "io.mehe.Expecting") ?? NSBundle.mainBundle()
  
  static func validate() throws {
    try storyboard.validate()
  }
  
  struct nib {
    private init() {}
  }
  
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      try app.validate()
      try onboard.validate()
    }
    
    struct app: StoryboardResourceType, Rswift.Validatable {
      let app_calendar = StoryboardViewControllerResource<CalendarVC>(identifier: "app_calendar")
      let app_feed = StoryboardViewControllerResource<FeedVC>(identifier: "app_feed")
      let app_home = StoryboardViewControllerResource<HomeVC>(identifier: "app_home")
      let app_lifeline = StoryboardViewControllerResource<LifeLineVC>(identifier: "app_lifeline")
      let app_tab = StoryboardViewControllerResource<TabBarController>(identifier: "app_tab")
      let bundle = _R.hostingBundle
      let name = "App"
      
      func app_calendar(_: Void) -> CalendarVC? {
        return UIStoryboard(resource: self).instantiateViewController(app_calendar)
      }
      
      func app_feed(_: Void) -> FeedVC? {
        return UIStoryboard(resource: self).instantiateViewController(app_feed)
      }
      
      func app_home(_: Void) -> HomeVC? {
        return UIStoryboard(resource: self).instantiateViewController(app_home)
      }
      
      func app_lifeline(_: Void) -> LifeLineVC? {
        return UIStoryboard(resource: self).instantiateViewController(app_lifeline)
      }
      
      func app_tab(_: Void) -> TabBarController? {
        return UIStoryboard(resource: self).instantiateViewController(app_tab)
      }
      
      static func validate() throws {
        if UIImage(named: "interface") == nil { throw ValidationError(description: "[R.swift] Image named 'interface' is used in storyboard 'App', but couldn't be loaded.") }
        if UIImage(named: "calendar") == nil { throw ValidationError(description: "[R.swift] Image named 'calendar' is used in storyboard 'App', but couldn't be loaded.") }
        if UIImage(named: "people-shout") == nil { throw ValidationError(description: "[R.swift] Image named 'people-shout' is used in storyboard 'App', but couldn't be loaded.") }
        if UIImage(named: "home") == nil { throw ValidationError(description: "[R.swift] Image named 'home' is used in storyboard 'App', but couldn't be loaded.") }
        if _R.storyboard.app().app_calendar() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'app_calendar' could not be loaded from storyboard 'App' as 'CalendarVC'.") }
        if _R.storyboard.app().app_lifeline() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'app_lifeline' could not be loaded from storyboard 'App' as 'LifeLineVC'.") }
        if _R.storyboard.app().app_feed() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'app_feed' could not be loaded from storyboard 'App' as 'FeedVC'.") }
        if _R.storyboard.app().app_home() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'app_home' could not be loaded from storyboard 'App' as 'HomeVC'.") }
        if _R.storyboard.app().app_tab() == nil { throw ValidationError(description:"[R.swift] ViewController with identifier 'app_tab' could not be loaded from storyboard 'App' as 'TabBarController'.") }
      }
      
      private init() {}
    }
    
    struct launchScreen: StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIViewController
      
      let bundle = _R.hostingBundle
      let name = "LaunchScreen"
      
      private init() {}
    }
    
    struct onboard: StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UINavigationController
      
      let bundle = _R.hostingBundle
      let name = "Onboard"
      
      static func validate() throws {
        if UIImage(named: "Baby Pic") == nil { throw ValidationError(description: "[R.swift] Image named 'Baby Pic' is used in storyboard 'Onboard', but couldn't be loaded.") }
        if UIImage(named: "Line") == nil { throw ValidationError(description: "[R.swift] Image named 'Line' is used in storyboard 'Onboard', but couldn't be loaded.") }
      }
      
      private init() {}
    }
    
    private init() {}
  }
  
  private init() {}
}